---
title: "Fish Microplastics Analysis"
author: "Mabon Young, John Calzini, and Gordon Maguire"
date: "2/7/2024"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
# install.packages("tidyverse")
# install.packages("readxl")
# install.packages("janitor")

library(tidyverse)
library(readxl)
library(janitor)
library(RColorBrewer)
library(forcats)
library(ggridges)
```

```{r load-dataset}
fish_microplastics <- read_xlsx("data/Fish_Microplastics_Data_Repository.xlsx", 
                                na = "NA") %>%
  janitor::clean_names() 

glimpse(fish_microplastics) 

#Sieve size is still a character, some of the entries have um after them, will need to figure out how to fix that later. Could also convert hot needle into a logical vector.
```

```{r fixdacolumns}
fish_microplastics <- fish_microplastics %>%
  mutate(sieve_size = str_extract(sieve_size, pattern = "[:digit:]+")) %>%
  mutate(sieve_size = case_when(sieve_size == "LG" ~ 777,
          TRUE ~ as.numeric(sieve_size))) %>%
  mutate(hot_needle = case_when(hot_needle == "yes" ~ TRUE, hot_needle == "no" ~ FALSE)) %>%
  mutate(fish_id = case_when(fish_id == "OC 14" ~ "Oc 14", TRUE ~ fish_id))
```


```{r ,fig.alt="This histogram shows the distribution of colored microplastics within the fish. The overwhelming majority of microplastics found were transparent with Black and blue being the second and third most common color."}
ggplot(data = fish_microplastics, mapping = aes(x = net_sample_mass_g)) +
  geom_histogram(binwidth = 1000) + 
  facet_wrap(~color) 
#You could also present this information in a bar graph, a histogram with a binwidth of 1000 will always be just 1 bar. Also, I wonder why we're seeing negative values? It's probably a result of overly large binwidth, but maybe ask Laurie about that.

ggplot(data = fish_microplastics, mapping = aes(x = net_sample_mass_g)) +
  geom_histogram(binwidth = 5) + 
  facet_wrap(~color) 

# This graph still isn't telling us that much; remember, the net sample mass isn't the mass of the plastic, it's the mass of the sample the plastic was taken from. It could still be helpful if we wanted to look at microplastic density, though! 
plastic_dens <- fish_microplastics %>%
  group_by(fish_id) %>%
  reframe(plastic_density = sum(quantity)/net_sample_mass_g, na.rm = TRUE, sample_type) %>%
  distinct(fish_id, sample_type, plastic_density)

fish_microplastics_dens <- fish_microplastics %>%
  mutate(plastic_density = quantity/net_sample_mass_g)
```

```{r}
fish_microplastics %>%
  group_by(color) %>%
  summarize(
    avg_ht = mean(quantity, na.rm = TRUE)
    ) %>% 
  arrange(desc(avg_ht)) %>% 
slice(1:5) 
```
```{r}
fish_microplastics %>% 
group_by(color) %>%
  summarize(
    avg_ht = mean(quantity, na.rm = TRUE), median = median(quantity, na.rm = TRUE), min = min(quantity, na.rm = TRUE), max = max(quantity, na.rm = TRUE), sd = sd(quantity, na.rm = TRUE), IQR = IQR(quantity, na.rm = TRUE)
    )

#That 109 one is a bit terrifying... maybe we could hone in on that fish and see if there's anything unique about it in the spatial data?
```
```{r add-station}
fish_microplastics_full <- fish_microplastics_dens %>%
  mutate(station = case_when(collection_lat == 27.31513 ~ "Sarasota", 
                             collection_lat == 27.42136 ~ "Longboat Key"))
```

```{r dens-by-station, fig.alt= "A scatter chart of microplastic quantity by sample mass for the Longboat Key and Sarasota sampling stations showing that microplastics are much more abundant in the Longboat Key samples, even at low sample masses."}
fish_microplastics_full %>%
  ggplot(aes(x = net_sample_mass_g, y = quantity, color = sample_type)) +
  geom_point() +
  facet_wrap(~station) +
  scale_colour_viridis_d() +
  labs( x = "Sample Mass (g)",
        y = "Quantity",
        color = "Sample Type",
        title = "Quantity of Microplastic Particles in Samples of Different Weights"
    )
```

```{r station-part-type, fig.alt= "A bar graph of the amount of different types of particles at each research station, showing that the Longboat Key station had more particles overall, with significantly more single fibers than Sarasota, with Sarasota having slightly more miscellaneous, uncategorized particles."}
fish_microplastics_full %>%
  drop_na(particle_type) %>%
  ggplot(aes(x = fct_relevel(particle_type, "Fiber_single", "Fiber_bundle", "Film", "Fragment_TWP", "Fragment_nonTWP" ), y = quantity, fill = sample_type)) +
  geom_col() +
  facet_wrap(~station) +
  scale_x_discrete(labels = c("Single Fiber", "Fiber Bundle", "Film", "Tire Wear", "Other")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_fill_viridis_d() +
  labs(x = "Particle Type", 
       y = "Quantity", 
       fill = "Sample Type",
       title = "Quantity of Particle Types Between Research Stations" )
```
```{r quant-density, fig.alt="In this ridgeline plot, we can see the different individual fish that were collected and the quantity of microplastics within them. We can see that most of the fish had a similar density of microplastics at the lower end of the scale, with some individuals having spikes of concentration at higher levels."}
fish_microplastics %>%
  group_by(fish_id) %>%
  filter(quantity < 60) %>%
  ggplot(aes(x = quantity, y = fish_id, fill = fish_id, show.legend = FALSE)) +
  geom_density_ridges() +
  theme(legend.position = "none") +
  scale_fill_viridis_d() +
  labs(x = "Quantity Distribution",
       y = "Fish ID",
       title = "Quantity Distribution Density by Individual Fish")
```
```{r color-freq, fig.alt= "A set of histograms showing the frequency of different colors of microplastic colors, where transparent, black, blue, and yellowed particles are by far the most common. It also shows that most of the fiber bundles are transparent, and all of the tire wear particles are black."}
# color.labs <- c("Black", "Blue", "Brown", "Green", "Multi", "Orange", "Pink", "Purple", "Red", "Transparent", "Yellow", "Yellowed")
# names(color.labs) <- c("Black", "Blue", "Brown", "Green", "Multi", "Orange", "Pink", "Purple", "Red", "Transparent", "Yellow", "Yellowed")

fish_microplastics %>%
  drop_na(particle_type) %>%
  ggplot(aes(x = quantity, fill = fct_relevel(particle_type, "Fiber_single", "Fiber_bundle", "Film", "Fragment_TWP", "Fragment_nonTWP" ))) +
  geom_histogram(binwidth = 5) + 
  facet_wrap(~color) +
  scale_fill_viridis_d(labels = c("Single Fiber", "Fiber Bundle", "Film", "Tire Wear Fragment", "Other Fragment")) +
  labs(x = "Quantity",
       y = "Occurences",
       title = "Frequency of Microplastic Particle Colors",
       fill = "Particle Type")

```

