---
title: "Project proposal"
author: "THE Triangle"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
```

## 1. Introduction
Microplastics have become more and more well known throughout the world in the past few years. We now recognize that they are an incredibly dangerous bi-product to marine life and many organizations have begun to attack the problem. That is what this project is about


## 2. Data
Our data concerns the average count of microplastics found in the stomachs of fish that are a common prey species for the dolphins in Sarasota Bay. We found this on the dryad website which is a library for many kinds of data sets.

## 3. Ethics review
We did not collect this data so there was no ethical issue of us cutting up the fish. 

## 4. Data analysis plan
With the data we plan on plotting it in a spatial manner. We want to see where these fish were gathered and if there is any correlation. We also want to see if there is a correlation between different fish and the average count of micro plastics found within it. It would be interesting to see if multiple variables like the distinct IDs and the average count have any correlation.


